### ISSUE TITLE
Changing FlashCard model to include simple spelling

### ISSUE THREAD

**Issue by Seblis** [Bad-Grandpa/ReadWriteExecute#11]
Most of database entries are written with kanji - for ease of use, we should display also hiragana/katakana spelling. For that we need to change models and views to accomodate new data.

Scripts inserting new data to database will be created separately from the project.

**Comment by Bad-Grandpa** [comment]
I agree also in the future hiragana/katakana spelling with intonation could be helpfull to learn the proper difference between kanji.

**Comment by Seblis** [comment]
Including intonation may prove to be more difficult to introduce since it isn't included in JMDict. For now I will add dual writing (kanji/simple) wherever applicable and I will research how to obtain intonation data in the meantime.

**Comment by Seblis** [comment]
Feature is basically ready, I will test and create pull request most likely tomorrow. As we are not ready for deployment yet, I suggest we can just create a new database (importdictionary command is ready for that). It will save some coding time and, frankly, it will be faster for PC than assigning kanji reading to existing entries. Otherwise I am ready to create proper migration with altering existing entries when it will have some advantages (i.e. when we have a production to maintain).
