### ISSUE TITLE
We should create application description and alpha version of documentation

### ISSUE THREAD

**Issue by Bad-Grandpa** [Bad-Grandpa/ReadWriteExecute#13]
In near future these could come in handy.

**Comment by Seblis** [comment]
I will create soon app description describing both basic features and virtual environment and requirements to build the project.

**Comment by Seblis** [comment]
Basic README.md created. @Bad-Grandpa please specify what kind of documentation do you mean in that particular issue.

**Comment by Bad-Grandpa** [comment]
Looks very good. Also I would include in near future some kind of "How to Use" document.
